
export default ipaToUnicode = [
    // Pulmonic Consonants
    {char: 'p', hex: '0070', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER P', ipaName: 'vl bilabial plosive'},
    {char: 'b', hex: '0062', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER B', ipaName: 'vd bilabial plosive'},
    {char: 'm', hex: '006D', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER M', ipaName: 'vd bilabial nasal'},
    {char: 'ʙ', hex: '0299', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL B', ipaName: 'vd bilabial trill'},
    {char: 'ɸ', hex: '0278', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER PHI', ipaName: 'vl bilabial fricative'},
    {char: 'β', hex: '03B2', range: 'Greek', unicodeName: 'GREEK SMALL LETTER BETA', ipaName: 'vd bilabial fricative'},
    {char: 'ɱ', hex: '0271', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER M W/ HOOK', ipaName: 'vd labiodental nasal'},
    {char: 'ⱱ', hex: '2C71', range: 'Latin-Extended C', unicodeName: 'LATIN SMALL LETTER V W/ RIGHT HOOK', ipaName: 'vd labiodental flap'},
    {char: 'f', hex: '0067', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER F', ipaName: 'vl labiodental fricative'},
    {char: 'v', hex: '0076', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER V', ipaName: 'vd labiodental fricative'},
    {char: 'ʋ', hex: '028B', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER V W/ HOOK', ipaName: 'vd labiodental approximant'},
    {char: 't', hex: '0074', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER T', ipaName: 'vl alveolar plosive'},
    {char: 'd', hex: '0064', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER D', ipaName: 'vd alveolar plosive'},
    {char: 'n', hex: '006E', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER N', ipaName: 'vd alveolar nasal'},
    {char: 'r', hex: '0072', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER R', ipaName: 'vd alveolar trill'},
    {char: 'ɾ', hex: '027E', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER R W/ FISHHOOK', ipaName: 'vd alveolar tap'},
    {char: 'θ', hex: '03B8', range: 'Greek', unicodeName: 'GREEK SMALL LETTER THETA', ipaName: 'vl dental fricative'},
    {char: 'ð', hex: '00F0', range: 'Latin-1 suppl.', unicodeName: 'LATIN SMALL LETTER ETH', ipaName: 'vd dental fricative'},
    {char: 's', hex: '0073', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER S', ipaName: 'vl alveolar fricative'},
    {char: 'z', hex: '007A', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER Z', ipaName: 'vd alveolar fricative'},
    {char: 'ʃ', hex: '0283', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER ESH', ipaName: 'vl postalveolar fricative'},
    {char: 'ʒ', hex: '0292', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER EZH', ipaName: 'vd postalveolar fricative'},
    {char: 'ɬ', hex: '026C', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER L W/ BELT', ipaName: 'vl lateral alveolar fricative'},
    {char: 'ɮ', hex: '026E', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER LEZH', ipaName: 'vd lateral alveolar fricative'},
    {char: 'ɹ', hex: '0279', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED R', ipaName: 'vd alveolar approximant'},
    {char: 'l', hex: '006C', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER L', ipaName: 'vd lateral alveolar approximant'},
    {char: 'ʈ', hex: '0288', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER T W/ RETROFLEX HOOK', ipaName: 'vl retroflex plosive'},
    {char: 'ɖ', hex: '0256', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER D W/ TAIL', ipaName: 'vd retroflex plosive'},
    {char: 'ɳ', hex: '0273', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER N W/ RETROFLEX HOOK', ipaName: 'vd retroflex nasal'},
    {char: 'ɽ', hex: '027D', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER R W/ TAIL', ipaName: 'vd retroflex flap'},
    {char: 'ʂ', hex: '0282', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER S W/ HOOK', ipaName: 'vl retroflex fricative'},
    {char: 'ʐ', hex: '0290', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER Z W/ RETROFLEX HOOK', ipaName: 'vd retroflex fricative'},
    {char: 'ɻ', hex: '027B', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED R W/ HOOK', ipaName: 'vd retroflex approximant'},
    {char: 'ɭ', hex: '026D', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER L W/ RETROFLEX HOOK', ipaName: 'vd retroflex lateral approximant'},
    {char: 'c', hex: '0063', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER C', ipaName: 'vl palatal plosive'},
    {char: 'ɟ', hex: '025F', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER DOTLESS J W/ STROKE', ipaName: 'vd palatal plosive'},
    {char: 'ɲ', hex: '0272', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER N W/ LEFT HOOK', ipaName: 'vd palatal nasal'},
    {char: 'ç', hex: '00E7', range: 'Latin-1 suppl.', unicodeName: 'LATIN SMALL LETTER C W/ CEDILLA', ipaName: 'vl palatal fricative'},
    {char: 'ʝ', hex: '029D', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER J W/ CROSSED-TAIL', ipaName: 'vd palatal fricative'},
    {char: 'j', hex: '006A', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER J', ipaName: 'vd palatal approximant'},
    {char: 'ʎ', hex: '028E', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED Y', ipaName: 'vd palatal lateral approximant'},
    {char: 'k', hex: '006B', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER K', ipaName: 'vl velar plosive'},
    {char: 'ɡ', hex: '0261', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER SCRIPT G', ipaName: 'vd velar plosive'},
    {char: 'ŋ', hex: '014B', range: 'Latin-Extended A', unicodeName: 'LATIN SMALL LETTER ENG', ipaName: 'vd velar nasal'},
    {char: 'x', hex: '0078', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER X', ipaName: 'vl velar fricative'},
    {char: 'ɣ', hex: '0263', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER GAMMA', ipaName: 'vd velar fricative'},
    {char: 'ɰ', hex: '0270', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED M W/ LONG LEG', ipaName: 'vd velar approximant'},
    {char: 'ʟ', hex: '029F', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL L', ipaName: 'vd velar lateral approximant'},
    {char: 'q', hex: '0071', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER Q', ipaName: 'vl uvular plosive'},
    {char: 'ɢ', hex: '0262', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL G', ipaName: 'vd uvular plosive'},
    {char: 'ɴ', hex: '0274', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL N', ipaName: 'vd uvular nasal'},
    {char: 'ʀ', hex: '0280', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL R', ipaName: 'vd uvular trill'},
    {char: 'χ', hex: '03C7', range: 'Greek', unicodeName: 'GREEK SMALL LETTER CHI', ipaName: 'vl uvular fricative'},
    {char: 'ʁ', hex: '0281', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL INVERTED R', ipaName: 'vd uvular fricative'},
    {char: 'ħ', hex: '0127', range: 'Latin-Extended A', unicodeName: 'LATIN SMALL LETTER H W/ STROKE', ipaName: 'vl pharyngeal fricative'},
    {char: 'ʕ', hex: '0295', range: 'IPA Extensions', unicodeName: 'LATIN LETTER PHARYNGEAL VOICED FRICATIVE', ipaName: 'vd pharyngeal fricative'},
    {char: 'ʔ', hex: '0294', range: 'IPA Extensions', unicodeName: 'LATIN LETTER GLOTTAL STOP', ipaName: 'vl glottal plosive'},
    {char: 'h', hex: '0068', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER H', ipaName: 'vl glottal fricative'},
    {char: 'ɦ', hex: '0266', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER H W/ HOOK', ipaName: 'vd glottal fricative'},

    //Non-pulmonic consonants
    {char: 'ʘ', hex: '0298', range: 'IPA Extensions', unicodeName: 'LATIN LETTER BILABIAL CLICK', ipaName: 'bilabial click'},
    {char: 'ǀ', hex: '01C0', range: 'Latin-Extended B', unicodeName: 'LATIN LETTER DENTAL CLICK', ipaName: 'dental click'},
    {char: 'ǃ', hex: '01C3', range: 'Latin-Extended B', unicodeName: 'LATIN LETTER RETROFLEX CLICK', ipaName: '(post)alveolar click'},
    {char: 'ǂ', hex: '01C2', range: 'Latin-Extended B', unicodeName: 'LATIN LETTER ALVEOLAR CLICK', ipaName: 'palatoalveolar click'},
    {char: 'ǁ', hex: '01C1', range: 'Latin-Extended B', unicodeName: 'LATIN LETTER LATERAL CLICK', ipaName: 'alveolar lateral click'},
    {char: 'ɓ', hex: '0253', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER B W/ HOOK', ipaName: 'vd bilabial implosive'},
    {char: 'ɗ', hex: '0257', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER D W/ HOOK', ipaName: 'vd dental/alveolar implosive'},
    {char: 'ʄ', hex: '0284', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER DOTLESS J W/ STROKE AND HOOK', ipaName: 'vd palatal implosive'},
    {char: 'ɠ', hex: '0260', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER G W/ HOOK', ipaName: 'vd velar implosive'},
    {char: 'ʛ', hex: '029B', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL G W/ HOOK', ipaName: 'vd uvular implosive'},
    {char: 'ʼ', hex: '02BC', range: 'Spacing mod. letters', unicodeName: 'MODIFIER LETTER APOSTROPHE', ipaName: 'ejective diacritic'},

    //Other Symbols
    {char: 'ʍ', hex: '028D', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED W', ipaName: 'vl labial-velar fricative'},
    {char: 'w', hex: '0077', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER W', ipaName: 'vd labial-velar approximant'},
    {char: 'ɥ', hex: '0265', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED H', ipaName: 'vd labial-palatal approximant'},
    {char: 'ʜ', hex: '029C', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL H', ipaName: 'vl epiglottal fricative'},
    {char: 'ʢ', hex: '02A2', range: 'IPA Extensions', unicodeName: 'LATIN LETTER REVERSED GLOTTAL STOP W/ STROKE', ipaName: 'vd epiglottal fricative'},
    {char: 'ʡ', hex: '02A1', range: 'IPA Extensions', unicodeName: 'LATIN LETTER GLOTTAL STOP W/ STROKE', ipaName: 'vd epiglottal plosive'},
    {char: 'ɕ', hex: '0255', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER C W/ CURL', ipaName: 'vl  alveolo-palatal  fricative'},
    {char: 'ʑ', hex: '0291', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER Z W/ CURL', ipaName: 'vd alveolo-palatal  fricative'},
    {char: 'ɺ', hex: '027A', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED R W/ LONG LEG', ipaName: 'vd alveolar lateral flap'},
    {char: 'ɧ', hex: '0267', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER HENG W/ HOOK', ipaName: 'simultaneous ʃ and x'},

    //Vowels
    {char: 'i', hex: '0069', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER I', ipaName: 'close front unrounded vowel'},
    {char: 'y', hex: '0079', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER Y', ipaName: 'close front rounded vowel'},
    {char: 'ɪ', hex: '026A', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL I', ipaName: 'lowered-close front unrounded vowel'},
    {char: 'ʏ', hex: '028F', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL Y', ipaName: 'lowered-close front rounded vowel'},
    {char: 'e', hex: '0065', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER E', ipaName: 'close-mid front unrounded vowel'},
    {char: 'ø', hex: '00F8', range: 'Latin-1 supplement', unicodeName: 'LATIN SMALL LETTER O W/ STROKE', ipaName: 'close-mid front rounded vowel'},
    {char: 'ɛ', hex: '025B', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER OPEN E', ipaName: 'open-mid front unrounded vowel'},
    {char: 'œ', hex: '0153', range: 'Latin-Extended A', unicodeName: 'LATIN SMALL LIGATURE OE', ipaName: 'open-mid front rounded vowel'},
    {char: 'æ', hex: '00E6', range: 'Latin-1 supplement', unicodeName: 'LATIN SMALL LETTER AE', ipaName: 'raised-open front unrounded vowel'},
    {char: 'a', hex: '0061', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER A', ipaName: 'open front unrounded vowel'},
    {char: 'ɶ', hex: '0276', range: 'IPA Extensions', unicodeName: 'LATIN LETTER SMALL CAPITAL OE', ipaName: 'open front rounded vowel'},
    {char: 'ɨ', hex: '0268', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER I W/ STROKE', ipaName: 'close central unrounded vowel'},
    {char: 'ʉ', hex: '0289', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER U BAR', ipaName: 'close central rounded vowel'},
    {char: 'ɘ', hex: '0258', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER REVERSED E', ipaName: 'close-mid central unrounded vowel'},
    {char: 'ɵ', hex: '0275', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER BARRED O', ipaName: 'close-mid central rounded vowel'},
    {char: 'ə', hex: '0259', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER SCHWA', ipaName: 'mid central unrounded vowel'},
    {char: 'ɜ', hex: '025C', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER REVERSED OPEN E', ipaName: 'open-mid central unrounded vowel'},
    {char: 'ɞ', hex: '025E', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER CLOSED REVERSED OPEN E', ipaName: 'open-mid central rounded vowel'},
    {char: 'ɐ', hex: '2050', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED A', ipaName: 'raised-open central unrounded vowel'},
    {char: 'ɯ', hex: '026F', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED M', ipaName: 'close back unrounded vowel'},
    {char: 'u', hex: '0075', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER U', ipaName: 'close back rounded vowel'},
    {char: 'ʊ', hex: '028A', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER UPSILON', ipaName: 'lowered-close back rounded vowel'},
    {char: 'ɤ', hex: '0264', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER RAMS HORN', ipaName: 'close-mid back unrounded vowel'},
    {char: 'o', hex: '006F', range: 'Basic Latin', unicodeName: 'LATIN SMALL LETTER O', ipaName: 'close-mid back rounded vowel'},
    {char: 'ʌ', hex: '028C', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED V', ipaName: 'open-mid back unrounded vowel'},
    {char: 'ɔ', hex: '0254', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER OPEN O', ipaName: 'open-mid back rounded vowel'},
    {char: 'ɑ', hex: '0251', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER ALPHA', ipaName: 'open back unrounded vowel'},
    {char: 'ɒ', hex: '0252', range: 'IPA Extensions', unicodeName: 'LATIN SMALL LETTER TURNED ALPHA', ipaName: 'open back rounded vow'}
];